=== amanitamuscariaKF/CarTrek/standorte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="de">
		Adressen und Geodaten aller Carsharing-Standorte
		</xs:documentation>
	</xs:annotation>
    <xs:element name="standorte">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="city" maxOccurs="unbounded">
                                <xs:complexType>
                                   <xs:simpleContent>
                                       <xs:extension base="xs:string">
                                           <xs:attribute name="id" type="xs:ID"></xs:attribute>
                                       </xs:extension>
                                   </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="stationen">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="station" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"></xs:element>
                                        <xs:element name="geopos">
                                            <xs:complexType>
                                                <xs:attribute name="lat" type="xs:decimal"></xs:attribute>
                                                <xs:attribute name="lng" type="xs:decimal"></xs:attribute>
                                                <xs:attribute name="url" type="xs:anyURI"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="street" type="xs:string"></xs:element>
                                                    <xs:element name="number" type="xs:string"></xs:element>
                                                    <xs:element name="zip" type="xs:string"></xs:element>
                                                    <xs:element name="city">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="id" type="xs:IDREF"></xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="district" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                                    <xs:attribute name="cityref" type="xs:IDREF"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amanitamuscariaKF/CarTrek/standorte.xml
<?xml version="1.0" encoding="UTF-8" ?>
<standorte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="standorte.xsd">
<?xml-stylesheet type="text/xsl" href="standorte.xsl"?>
<cities>
    <city id="c100016">Bonn</city>
    <city id="c53">Fürth</city>
    <city id="c2502">Gießen</city>
    <city id="c34100">Kassel</city>
    <city id="c2500">Marburg</city>
    <city id="c90">München</city>
    <city id="c52">Nürnberg</city>
    <city id="c100012">Würzburg</city>
</cities>
<stationen>
    <station id="s400310" cityref="c100016">
        <name>Hauptbahnhof</name>
        <geopos lat="50.731085513638575" lng="7.097994089126587" url="https://www.google.com/maps/?q=50.731085513638575+7.097994089126587"></geopos>
        <address>
            <street>Quantiusstraße</street>
            <number>30-34</number>
            <zip>53111</zip>
            <city id="c100016">Bonn</city>
            <district>Zentrum</district>
        </address>
    </station>
    <station id="s402921" cityref="c100016">
        <name>Georgstraße/Chlodwigplatz</name>
        <geopos lat="50.74251835350631" lng="7.091808915138245" url="https://www.google.com/maps/?q=50.74251835350631+7.091808915138245"></geopos>
        <address>
            <street>Georgstraße</street>
            <number>28</number>
            <zip>53111</zip>
            <city id="c100016">Bonn</city>
            <district>Nordstadt</district>
        </address>
    </station>
    <station id="s403022" cityref="c100016">
        <name>Kaiserstraße/Königstraße</name>
        <geopos lat="50.729382655957934" lng="7.103565037250519" url="https://www.google.com/maps/?q=50.729382655957934+7.103565037250519"></geopos>
        <address>
            <street>Kaiserstraße</street>
            <number>52</number>
            <zip>53111</zip>
            <city id="c100016">Bonn</city>
            <district>Südstadt</district>
        </address>
    </station>
    <station id="s403067" cityref="c100016">
        <name>Godesberger Allee</name>
        <geopos lat="50.704659841304064" lng="7.132431641221046" url="https://www.google.com/maps/?q=50.704659841304064+7.132431641221046"></geopos>
        <address>
            <street>Godesberger Allee</street>
            <number>189</number>
            <zip>53175</zip>
            <city id="c100016">Bonn</city>
            <district></district>
        </address>
    </station>
    <station id="s403109" cityref="c100016">
        <name>Reuter Straße 76/DruckTechnik-RheinSieg</name>
        <geopos lat="50.721289925450655" lng="7.102968245744705" url="https://www.google.com/maps/?q=50.721289925450655+7.102968245744705"></geopos>
        <address>
            <street>Reuterstraße</street>
            <number>76</number>
            <zip>53113</zip>
            <city id="c100016">Bonn</city>
            <district>Südstadt</district>
        </address>
    </station>
    <station id="s403221" cityref="c100016">
        <name>Kesselgasse/studentshome</name>
        <geopos lat="50.73700793627685" lng="7.099748145388958" url="https://www.google.com/maps/?q=50.73700793627685+7.099748145388958"></geopos>
        <address>
            <street>Kesselgasse</street>
            <number>2</number>
            <zip>53111</zip>
            <city id="c100016">Bonn</city>
            <district>Zentrum</district>
        </address>
    </station>
    <station id="s403222" cityref="c100016">
        <name>Bahnhof Bonn-Beuel</name>
        <geopos lat="50.73822266478432" lng="7.127651165770885" url="https://www.google.com/maps/?q=50.73822266478432+7.127651165770885"></geopos>
        <address>
            <street>Beueler Bahnhofsplatz</street>
            <number>null</number>
            <zip>53225</zip>
            <city id="c100016">Bonn</city>
            <district>Beuel</district>
        </address>
    </station>
    <station id="s403223" cityref="c100016">
        <name>Bahnhof Bonn Bad Godesberg</name>
        <geopos lat="50.683677273624966" lng="7.160291612017318" url="https://www.google.com/maps/?q=50.683677273624966+7.160291612017318"></geopos>
        <address>
            <street>Von-Groote-Platz</street>
            <number>9</number>
            <zip>53173</zip>
            <city id="c100016">Bonn</city>
            <district>Bad Godesberg</district>
        </address>
    </station>
    <station id="s403404" cityref="c100016">
        <name>Eduard-Otto-Straße</name>
        <geopos lat="50.71667463313135" lng="7.108912020921707" url="https://www.google.com/maps/?q=50.71667463313135+7.108912020921707"></geopos>
        <address>
            <street>Eduard-Otto-Straße</street>
            <number>26-32</number>
            <zip>53129</zip>
            <city id="c100016">Bonn</city>
            <district>Kessenich</district>
        </address>
    </station>
    <station id="s403412" cityref="c100016">
        <name>Quartier Südstadt, Weststadt und Poppelsdorf</name>
        <geopos lat="50.72527381129086" lng="7.095236778259277" url="https://www.google.com/maps/?q=50.72527381129086+7.095236778259277"></geopos>
        <address>
            <street>Anwohnerparkzone A, G &amp; W sowie Straßen in Poppelsdorf</street>
            <number>null</number>
            <zip>53113</zip>
            <city id="c100016">Bonn</city>
            <district>Süd- / Weststadt / Poppelsdorf</district>
        </address>
    </station>
    <station id="s404689" cityref="c100016">
        <name>Giergasse</name>
        <geopos lat="50.735631446254544" lng="7.105667404539418" url="https://www.google.com/maps/?q=50.735631446254544+7.105667404539418"></geopos>
        <address>
            <street>Giergasse</street>
            <number>null</number>
            <zip>53113</zip>
            <city id="c100016">Bonn</city>
            <district>Zentrum</district>
        </address>
    </station>
    <station id="s404690" cityref="c100016">
        <name>Maxstraße</name>
        <geopos lat="50.738673107757236" lng="7.093546788655658" url="https://www.google.com/maps/?q=50.738673107757236+7.093546788655658"></geopos>
        <address>
            <street>Maxstraße</street>
            <number>46</number>
            <zip>53111</zip>
            <city id="c100016">Bonn</city>
            <district>Zentrum</district>
        </address>
    </station>
    <station id="s404691" cityref="c100016">
        <name>Bonner Talweg</name>
        <geopos lat="50.725563687204165" lng="7.102454206869879" url="https://www.google.com/maps/?q=50.725563687204165+7.102454206869879"></geopos>
        <address>
            <street>Bonner Talweg</street>
            <number>41</number>
            <zip>53115</zip>
            <city id="c100016">Bonn</city>
            <district>Südstadt</district>
        </address>
    </station>
    <station id="s404771" cityref="c100016">
        <name>Hauptbahnhof/Kaiserplatz</name>
        <geopos lat="50.731280045205985" lng="7.100578397512436" url="https://www.google.com/maps/?q=50.731280045205985+7.100578397512436"></geopos>
        <address>
            <street>Kaiserplatz</street>
            <number>15</number>
            <zip>53113</zip>
            <city id="c100016">Bonn</city>
            <district>Zentrum</district>
        </address>
    </station>
    <station id="s404994" cityref="c100016">
        <name>Südstadtgarage/Bonner Talweg</name>
        <geopos lat="50.72306549663528" lng="7.104165743636372" url="https://www.google.com/maps/?q=50.72306549663528+7.104165743636372"></geopos>
        <address>
            <street>Bonner Talweg</street>
            <number>83-89</number>
            <zip>53113</zip>
            <city id="c100016">Bonn</city>
            <district>Südstadt</district>
        </address>
    </station>
    <station id="s405184" cityref="c100016">
        <name>Zingsheimstrasse/Friedrich-Breuer-Straße</name>
        <geopos lat="50.73774321149575" lng="7.120605647432967" url="https://www.google.com/maps/?q=50.73774321149575+7.120605647432967"></geopos>
        <address>
            <street>Zingsheimstrasse</street>
            <number>4-8</number>
            <zip>53225</zip>
            <city id="c100016">Bonn</city>
            <district>Beuel</district>
        </address>
    </station>
    <station id="s406120" cityref="c100016">
        <name>Baumschulallee/Poppelsdorfer Allee</name>
        <geopos lat="50.73023982249019" lng="7.0972940325737" url="https://www.google.com/maps/?q=50.73023982249019+7.0972940325737"></geopos>
        <address>
            <street>Baumschulallee</street>
            <number>2</number>
            <zip>53115</zip>
            <city id="c100016">Bonn</city>
            <district>Weststadt</district>
        </address>
    </station>
    <station id="s406441" cityref="c100016">
        <name>Argelander Straße</name>
        <geopos lat="50.724413559962876" lng="7.098961550926219" url="https://www.google.com/maps/?q=50.724413559962876+7.098961550926219"></geopos>
        <address>
            <street>Argelander Straße</street>
            <number>70</number>
            <zip>53115</zip>
            <city id="c100016">Bonn</city>
            <district>Bonn</district>
        </address>
    </station>
    <station id="s406442" cityref="c100016">
        <name>Markusstraße</name>
        <geopos lat="50.714841" lng="7.11256" url="https://www.google.com/maps/?q=50.714841+7.11256"></geopos>
        <address>
            <street>Markusstraße</street>
            <number>4</number>
            <zip>53129</zip>
            <city id="c100016">Bonn</city>
            <district>Kessenich</district>
        </address>
    </station>
    <station id="s406544" cityref="c100016">
        <name>Haydnstraße</name>
